import { Grid } from '@mui/material'
import React, { forwardRef } from 'react'
import SvgTile from '../../SvgTile'
const index = forwardRef((prop, ref ) => {
  return (
    <Grid
      container
      alignItems={'center'}
      direction='row'
      width='550px'
      height='540px'
      justifyContent='center'
      sx={{ border: '1px solid black' }}
    >
      <Grid
        item
        className='polygon_container'
        width='550px'
        height='538px'

      >
        <Grid
          container
          alignItems={'center'}
          direction='row'
          ml='-27px'
          mt='-10px'
          justifyContent='flex-start'
        >
          <Grid item>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginTop: '-83px', marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '252px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginTop: '-83px', marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '252px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginTop: '-83px', marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '252px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginTop: '-83px', marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '252px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
        </Grid>
        <Grid
          container
          alignItems={'center'}
          direction='row'
          ml='-100px'
          mt='-7px'
          justifyContent='flex-start'
        >
          <Grid item>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginTop: '-83px', marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '252px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginTop: '-83px', marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '252px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginTop: '-83px', marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '252px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginTop: '-83px', marginLeft: '72px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '252px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
          <Grid item sx={{ marginLeft: '576px', marginTop: '-299px' }}>
            <Grid
              container
              height='300px'
              position='relative'
              direction='column'
            >
              <Grid
                item
                width='100px'
                height='100px'
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '84px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
              <Grid
                item
                width='100px'
                height='100px'
                sx={{ marginTop: '168px' }}
                position='absolute'
              >
                <SvgTile
                  ref={ref}
                  currentPattern={prop.currentPattern}
                  setCurrentPattern={prop.setCurrentPattern}
                  currentColor={prop.currentColor}
                />
              </Grid>
            </Grid>
          </Grid>
        </Grid>
      </Grid>
    </Grid>
  )
})

export default index
